Repository ssec-jhu/flfm, pull requests merged in 2025-07, with the labels that each got.

#193 Add Some Documentation to the code and Sphinx
  docs/Makefile
  docs/source/api.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/usage.rst
  flfm/app/main.py
  flfm/backend/base.py
  flfm/backend/jax.py
  flfm/backend/torch.py
  flfm/batch.py
  flfm/cli.py
  flfm/restoration.py
  flfm/settings.py
  flfm/util.py
  requirements/docs.txt
Labels: documentation

#194 Add very brief quickstart instructions
  README.md
Labels: documentation

#195 Run CI on Windows
  .github/workflows/ci.yml
Labels: CI

#197 192 add batch feature to cli
  flfm/batch.py
  flfm/cli.py
  flfm/settings.py
  flfm/tests/test_batch.py
  flfm/tests/test_cli.py
  flfm/util.py
  tests/test_util.py
Labels: enhancement

#209 Add refs in doc to imagej plgin repo
  README.md
  docs/source/usage.rst
Labels: documentation

#210 Rename and update dockerfile data src path
  docker/Dockerfile.cpp_code
  docker/Dockerfile.olaf
  docker/Dockerfile.python
Labels: bug, docker

#199 Limit JAX GPU memory preallocation
  flfm/backend/jax.py
  flfm/settings.py
Labels: perf, jax, pytorch, project-close-must-have

#215 Add settings.TIME_RECONSTRUCTION
  flfm/restoration.py
  flfm/settings.py
Labels: enhancement, perf, future
