Repository ssec-jhu/flfm, pull requests merged in 2025-05, with the labels that each got.

#150 Update docs link in README
  README.md
Labels: documentation

#156 Update zenodo.json
  .zenodo.json
  CITATION.cff
Labels: documentation

#161 Update DOI in README.md
  README.md
Labels: documentation

#69 Simulated psf
  data/yale/psf_calibration.txt
  notebooks/Simulated_PSF_and_Reconstruction.ipynb
Labels: notebook

#149 Add batch processing helper funcs
  flfm/batch.py
  flfm/pytorch_restoration.py
  flfm/restoration.py
  flfm/settings.py
  flfm/tests/test_batch.py
  flfm/util.py
  pyproject.toml
  requirements/prd.txt
  tests/test_util.py
Labels: enhancement

#173 Move data dir inside the package
  README.md
  docker/Dockerfile.flfm
  docker/Dockerfile.java.pytorch
  flfm/src/cpp/Reconstruct_FLFM.cpp
  flfm/tests/data/yale/light_field_image.tif
  flfm/tests/data/yale/measured_psf.tif
  flfm/tests/data/yale/psf_calibration.txt
  flfm/tests/test_batch.py
  flfm/tests/test_data.py
  flfm/tests/test_restoration.py
  notebooks/Simulated_PSF_and_Reconstruction.ipynb
  notebooks/jax_flfm.ipynb
  notebooks/pytorch_flfm.ipynb
  tests/test_util.py
Labels: documentation, CI

#142 Simple Plotly/Dash UI
  README.md
  flfm/app/__init__.py
  flfm/app/main.py
  flfm/app/tests/__init__.py
  flfm/app/tests/test_app.py
  flfm/cli.py
  flfm/settings.py
  flfm/util.py
  pyproject.toml
  requirements/app.txt
  requirements/test.txt
  tox.ini
Labels: UI
